"""
OpenAPI/Swagger Configuration for SigmaFlow API
================================================
Enhances the FastAPI application with comprehensive OpenAPI documentation.
"""

from fastapi import FastAPI
from fastapi.openapi.utils import get_openapi


# OpenAPI Tags with descriptions
TAGS_METADATA = [
    {
        "name": "authentication",
        "description": "Authentication and authorization endpoints. Includes login, registration, token refresh, and user profile management.",
        "externalDocs": {
            "description": "Auth Guide",
            "url": "https://docs.sigmaflow.example.com/auth",
        },
    },
    {
        "name": "tenants",
        "description": "Multi-tenant management. Create, list, and retrieve tenants. Superuser access required for creation.",
    },
    {
        "name": "plants",
        "description": "Plant/facility management within tenants. Plants represent physical locations where projects execute.",
    },
    {
        "name": "projects",
        "description": "DMAIC project management. Create, list, update, and delete Lean Six Sigma projects.",
    },
    {
        "name": "datasets",
        "description": "Dataset management for projects. Upload and manage data sources for statistical analysis.",
    },
    {
        "name": "runs",
        "description": "Pipeline execution management. Trigger, monitor, and retrieve results of DMAIC pipeline runs.",
    },
    {
        "name": "insights",
        "description": "Statistical insights generated by the pipeline. Includes SPC alerts, capability analysis, and recommendations.",
    },
    {
        "name": "action-items",
        "description": "Action item tracking for improvement projects. Create, assign, and track verification of corrective actions.",
    },
    {
        "name": "scheduled-runs",
        "description": "Scheduled pipeline execution. Configure cron-based automated runs for continuous monitoring.",
    },
    {
        "name": "alerts",
        "description": "SPC alert webhooks and subscriptions. Real-time notifications for out-of-control processes.",
    },
    {
        "name": "health",
        "description": "System health checks and diagnostics. Database connectivity, service status, and version info.",
    },
]


# Component schemas for reuse
COMPONENT_SCHEMAS = {
    "ErrorResponse": {
        "type": "object",
        "properties": {
            "detail": {
                "type": "string",
                "description": "Human-readable error description",
            },
            "error_code": {
                "type": "string",
                "description": "Machine-readable error code",
            },
            "timestamp": {
                "type": "string",
                "format": "date-time",
                "description": "Error occurrence timestamp",
            },
            "path": {
                "type": "string",
                "description": "Request path that caused the error",
            },
        },
        "required": ["detail"],
    },
    "PaginatedResponse": {
        "type": "object",
        "properties": {
            "items": {"type": "array", "items": {"type": "object"}},
            "total": {"type": "integer", "description": "Total number of items"},
            "page": {"type": "integer", "description": "Current page number"},
            "page_size": {"type": "integer", "description": "Items per page"},
            "total_pages": {"type": "integer", "description": "Total number of pages"},
        },
    },
    "HealthCheckResponse": {
        "type": "object",
        "properties": {
            "status": {
                "type": "string",
                "enum": ["healthy", "degraded", "unhealthy"],
                "description": "Overall system health status",
            },
            "database": {
                "type": "string",
                "enum": ["connected", "disconnected", "degraded"],
                "description": "Database connection status",
            },
            "redis": {
                "type": "string",
                "enum": ["connected", "disconnected"],
                "description": "Redis connection status",
            },
            "version": {"type": "string", "description": "API version"},
            "uptime_seconds": {"type": "number", "description": "Service uptime in seconds"},
        },
    },
}


# Security schemes
SECURITY_SCHEMES = {
    "BearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "description": "JWT Bearer token authentication. Obtain token from `/api/v1/auth/login`.",
    },
    "ApiKeyAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "X-API-Key",
        "description": "API Key authentication for service-to-service communication.",
    },
}


# Example responses for common patterns
EXAMPLE_RESPONSES = {
    400: {
        "description": "Bad Request - Invalid input data",
        "content": {
            "application/json": {
                "schema": {"$ref": "#/components/schemas/ErrorResponse"},
                "example": {
                    "detail": "Validation error: field 'email' is not a valid email address",
                    "error_code": "VALIDATION_ERROR",
                    "timestamp": "2024-01-15T10:30:00Z",
                    "path": "/api/v1/projects",
                },
            }
        },
    },
    401: {
        "description": "Unauthorized - Invalid or missing authentication",
        "content": {
            "application/json": {
                "schema": {"$ref": "#/components/schemas/ErrorResponse"},
                "example": {
                    "detail": "Could not validate credentials",
                    "error_code": "UNAUTHORIZED",
                    "timestamp": "2024-01-15T10:30:00Z",
                    "path": "/api/v1/projects",
                },
            }
        },
    },
    403: {
        "description": "Forbidden - Insufficient permissions",
        "content": {
            "application/json": {
                "schema": {"$ref": "#/components/schemas/ErrorResponse"},
                "example": {
                    "detail": "Insufficient permissions to create projects. Required: PROJECT_WRITE",
                    "error_code": "FORBIDDEN",
                    "timestamp": "2024-01-15T10:30:00Z",
                    "path": "/api/v1/projects",
                },
            }
        },
    },
    404: {
        "description": "Not Found - Resource does not exist",
        "content": {
            "application/json": {
                "schema": {"$ref": "#/components/schemas/ErrorResponse"},
                "example": {
                    "detail": "Project not found",
                    "error_code": "NOT_FOUND",
                    "timestamp": "2024-01-15T10:30:00Z",
                    "path": "/api/v1/projects/123e4567-e89b-12d3-a456-426614174000",
                },
            }
        },
    },
    409: {
        "description": "Conflict - Resource already exists",
        "content": {
            "application/json": {
                "schema": {"$ref": "#/components/schemas/ErrorResponse"},
                "example": {
                    "detail": "Project code already exists in tenant",
                    "error_code": "CONFLICT",
                    "timestamp": "2024-01-15T10:30:00Z",
                    "path": "/api/v1/projects",
                },
            }
        },
    },
    422: {
        "description": "Unprocessable Entity - Validation error",
        "content": {
            "application/json": {
                "schema": {"$ref": "#/components/schemas/ErrorResponse"},
                "example": {
                    "detail": [
                        {
                            "loc": ["body", "email"],
                            "msg": "value is not a valid email address",
                            "type": "value_error.email",
                        }
                    ],
                    "error_code": "VALIDATION_ERROR",
                    "timestamp": "2024-01-15T10:30:00Z",
                    "path": "/api/v1/auth/register",
                },
            }
        },
    },
    500: {
        "description": "Internal Server Error",
        "content": {
            "application/json": {
                "schema": {"$ref": "#/components/schemas/ErrorResponse"},
                "example": {
                    "detail": "Internal server error",
                    "error_code": "INTERNAL_ERROR",
                    "timestamp": "2024-01-15T10:30:00Z",
                    "path": "/api/v1/projects",
                },
            }
        },
    },
    503: {
        "description": "Service Unavailable - Dependencies not ready",
        "content": {
            "application/json": {
                "schema": {"$ref": "#/components/schemas/ErrorResponse"},
                "example": {
                    "detail": "Database connection unavailable",
                    "error_code": "SERVICE_UNAVAILABLE",
                    "timestamp": "2024-01-15T10:30:00Z",
                    "path": "/api/v1/projects",
                },
            }
        },
    },
}


def custom_openapi(app: FastAPI) -> dict:
    """
    Generate custom OpenAPI schema with enhanced documentation.
    """
    if app.openapi_schema:
        return app.openapi_schema

    openapi_schema = get_openapi(
        title="SigmaFlow API",
        version="0.2.0",
        description="""
# SigmaFlow Enterprise API

**Enterprise Lean Six Sigma DMAIC Automation Platform**

SigmaFlow provides a comprehensive REST API for managing Lean Six Sigma projects using the DMAIC methodology (Define, Measure, Analyze, Improve, Control).

## Features

- **Multi-tenancy**: Isolated data and users per tenant/organization
- **Role-Based Access Control (RBAC)**: 5 roles (VIEWER, GREEN_BELT, BLACK_BELT, MBB, ADMIN) with 27 granular permissions
- **DMAIC Pipeline Automation**: Automated statistical analysis across all 5 phases
- **Real-time SPC Monitoring**: Western Electric rules, capability analysis, control charts
- **Action Item Tracking**: Full workflow for improvement actions with verification
- **Scheduled Execution**: Cron-based automated pipeline runs
- **Webhook Alerts**: Real-time notifications for process anomalies

## Authentication

All endpoints (except `/health` and `/api/v1/info`) require authentication via **JWT Bearer tokens**.

1. Obtain token: `POST /api/v1/auth/login` with `username` (email) and `password`
2. Use token: Include `Authorization: Bearer <token>` header in requests
3. Token expires in 30 minutes (configurable), use refresh token for renewal

## Multi-Tenancy

All resources are scoped to the authenticated user's tenant:
- Users can only access resources within their tenant
- Superusers can access all tenants
- Tenant isolation is enforced at database and API levels

## RBAC Permissions

| Role | Description | Key Permissions |
|------|-------------|-----------------|
| VIEWER | Read-only access | PROJECT_READ, PLANT_READ |
| GREEN_BELT | Project execution | PROJECT_WRITE, DATASET_WRITE, RUN_CREATE |
| BLACK_BELT | Advanced analysis | All GREEN_BELT + INSIGHT_MANAGE |
| MBB | Master Black Belt | All BLACK_BELT + TENANT_READ, USER_MANAGE |
| ADMIN | Tenant administrator | All permissions including TENANT_WRITE |

## Rate Limits

- **Authenticated requests**: 1000 requests/minute per user
- **Login attempts**: 10 requests/minute per IP
- **Pipeline triggers**: 50 requests/minute per project

## Versioning

API version is included in the URL path: `/api/v1/`
Breaking changes will increment the version (v2, v3, etc.)

## Support

- Documentation: https://docs.sigmaflow.example.com
- Issues: https://github.com/OsvaldinoJunior/SigmaFlow/issues
- Email: support@sigmaflow.example.com
        """,
        routes=app.routes,
        tags=TAGS_METADATA,
        servers=[
            {"url": "http://localhost:8000", "description": "Local development server"},
            {"url": "https://staging.sigmaflow.example.com", "description": "Staging server"},
            {"url": "https://api.sigmaflow.example.com", "description": "Production server"},
        ],
        contact={
            "name": "SigmaFlow Team",
            "url": "https://github.com/OsvaldinoJunior/SigmaFlow",
            "email": "support@sigmaflow.example.com",
        },
        license_info={
            "name": "MIT License",
            "url": "https://opensource.org/licenses/MIT",
        },
    )

    # Add security schemes
    openapi_schema["components"]["securitySchemes"] = SECURITY_SCHEMES

    # Add component schemas
    openapi_schema["components"]["schemas"].update(COMPONENT_SCHEMAS)

    # Apply security globally (can be overridden per endpoint)
    openapi_schema["security"] = [{"BearerAuth": []}]

    # Enhance paths with better examples and responses
    for path, path_item in openapi_schema.get("paths", {}).items():
        for method, operation in path_item.items():
            if method in ("get", "post", "put", "patch", "delete", "head", "options", "trace"):
                # Add common error responses
                for code, response in EXAMPLE_RESPONSES.items():
                    if code not in operation.get("responses", {}):
                        operation.setdefault("responses", {})[str(code)] = response

                # Add request examples for POST/PUT/PATCH
                if method in ("post", "put", "patch") and "requestBody" in operation:
                    # Examples will be added per endpoint in main.py
                    pass

    app.openapi_schema = openapi_schema
    return app.openapi_schema


def setup_openapi(app: FastAPI) -> None:
    """
    Configure custom OpenAPI for the FastAPI application.
    Call this after creating the FastAPI app and adding all routes.
    """
    app.openapi = lambda: custom_openapi(app)