"""Add ScheduledRun model for cron scheduling

Revision ID: bcc71cb76eeb
Revises: 3a10ca836675
Create Date: 2026-07-28 04:11:18.848356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc71cb76eeb'
down_revision: Union[str, Sequence[str], None] = '3a10ca836675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('dataset_name', sa.String(length=120), nullable=True),
    sa.Column('run_config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheduled_runs_next_run', 'scheduled_runs', ['next_run_at'], unique=False)
    op.create_index('ix_scheduled_runs_project_enabled', 'scheduled_runs', ['project_id', 'enabled'], unique=False)
    # ### end Alembic commands ###
    # Note: SQLite doesn't support ALTER COLUMN type changes.
    # UUID type columns are already created correctly in the initial migration.
    # The alter_column operations below are only needed for PostgreSQL and are skipped for SQLite.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: SQLite doesn't support ALTER COLUMN type changes.
    # These operations are only needed for PostgreSQL.
    op.drop_index('ix_scheduled_runs_project_enabled', table_name='scheduled_runs')
    op.drop_index('ix_scheduled_runs_next_run', table_name='scheduled_runs')
    op.drop_table('scheduled_runs')
    # ### end Alembic commands ###
