"""
sigmaflow/analysis/transformations.py
=====================================
Data transformations for non-normal capability analysis.

Supports:
- Box-Cox transformation (positive data)
- Johnson transformation (any real data)
- Log transformation (simple positive data)

Based on Minitab/JMP methodology for non-normal capability analysis.
"""

from __future__ import annotations

import warnings
from typing import Any, Dict, Optional, Tuple, Literal

import numpy as np
import pandas as pd
from scipy import stats as sc_stats
from scipy.optimize import minimize_scalar
from scipy.special import boxcox1p, inv_boxcox

# ─── Box-Cox Transformation ────────────────────────────────────────────────────


def boxcox_transform(
    data: pd.Series,
    lambda_val: Optional[float] = None,
) -> Tuple[pd.Series, float, Dict[str, Any]]:
    """
    Apply Box-Cox transformation to make data more normal.

    Parameters
    ----------
    data : pd.Series
        Positive data to transform.
    lambda_val : float, optional
        Specific lambda to use. If None, finds optimal lambda via MLE.

    Returns
    -------
    tuple
        (transformed_data, lambda_used, metadata_dict)

    Notes
    -----
    Box-Cox: y' = (y^λ - 1) / λ  for λ ≠ 0
             y' = ln(y)          for λ = 0
    Requires all data > 0.
    """
    values = data.dropna().values
    if len(values) == 0:
        raise ValueError("No data to transform")

    if np.any(values <= 0):
        raise ValueError("Box-Cox requires all values > 0. Use Johnson for data with zeros/negatives.")

    if lambda_val is None:
        # Find optimal lambda using scipy's boxcox (MLE)
        transformed, lambda_opt = sc_stats.boxcox(values)
        lambda_used = float(lambda_opt)
    else:
        lambda_used = float(lambda_val)
        if lambda_used == 0:
            transformed = np.log(values)
        else:
            transformed = (np.power(values, lambda_used) - 1) / lambda_used

    metadata = {
        "method": "boxcox",
        "lambda": lambda_used,
        "original_min": float(np.min(values)),
        "original_max": float(np.max(values)),
        "transformed_min": float(np.min(transformed)),
        "transformed_max": float(np.max(transformed)),
        "n": len(values),
    }

    return pd.Series(transformed, index=data.dropna().index), lambda_used, metadata


def boxcox_inverse(transformed: pd.Series, lambda_val: float) -> pd.Series:
    """
    Inverse Box-Cox transformation.

    Parameters
    ----------
    transformed : pd.Series
        Transformed data.
    lambda_val : float
        Lambda used in forward transformation.

    Returns
    -------
    pd.Series
        Original-scale data.
    """
    if lambda_val == 0:
        return np.exp(transformed)
    return np.power(transformed * lambda_val + 1, 1 / lambda_val)


# ─── Johnson Transformation ────────────────────────────────────────────────────


def johnson_transform(
    data: pd.Series,
    method: Literal["SL", "SU", "SB"] = "auto",
) -> Tuple[pd.Series, Dict[str, Any]]:
    """
    Apply Johnson transformation for non-normal data.

    Johnson system covers three families:
    - SL (Log-normal): ln((y - ξ) / λ) ~ N(0,1)
    - SU (Unbounded): sinh⁻¹((y - ξ) / λ) ~ N(0,1)
    - SB (Bounded): ln((y - ξ) / (ξ + λ - y)) ~ N(0,1)

    Parameters
    ----------
    data : pd.Series
        Data to transform (can have any real values).
    method : str
        "auto" to select best fit via AD test, or specific family.

    Returns
    -------
    tuple
        (transformed_data, metadata_dict)

    References
    ----------
    Johnson, N. L. (1949). Systems of frequency curves generated by methods of translation.
    """
    values = data.dropna().values
    n = len(values)
    if n < 20:
        raise ValueError("Johnson transformation requires at least 20 observations")

    # Standardize for numerical stability
    std_val = np.std(values, ddof=1)
    if std_val == 0:
        raise ValueError("Constant data cannot be transformed")
    z = (values - np.mean(values)) / std_val

    # Fit all three Johnson families and pick best by Anderson-Darling on transformed
    families = {
        "SL": _fit_johnson_sl,
        "SU": _fit_johnson_su,
        "SB": _fit_johnson_sb,
    }

    best_family = None
    best_ad_stat = float("inf")
    best_params = None
    best_transformed = None

    families_to_try = [method] if method != "auto" else ["SL", "SU", "SB"]

    for fam in families_to_try:
        try:
            params, transformed_z = families[fam](z)
            # Test normality of transformed
            ad_result = sc_stats.anderson(transformed_z, dist="norm")
            ad_stat = ad_result.statistic
            if ad_stat < best_ad_stat:
                best_ad_stat = ad_stat
                best_family = fam
                best_params = params
                best_transformed = transformed_z * std_val + np.mean(values)  # re-scale
        except Exception:
            continue

    if best_family is None:
        raise RuntimeError("Could not fit any Johnson family")

    metadata = {
        "method": "johnson",
        "family": best_family,
        "params": best_params,
        "ad_statistic": float(best_ad_stat),
        "original_min": float(np.min(values)),
        "original_max": float(np.max(values)),
        "transformed_min": float(np.min(best_transformed)),
        "transformed_max": float(np.max(best_transformed)),
        "n": n,
    }

    return pd.Series(best_transformed, index=data.dropna().index), metadata


def _fit_johnson_sl(z: np.ndarray) -> Tuple[Dict[str, float], np.ndarray]:
    """Fit Johnson SL (log-normal): ln(z - ξ) ~ N(0,1) after scaling."""
    # SL: y = ξ + λ * exp(z)  =>  z = ln(y - ξ) - ln(λ)
    # For standardized z, we need to find ξ, λ such that transformed is normal
    # Use MLE approximation: match moments
    # SL requires all data > ξ
    # We'll use method of percentiles
    p10, p50, p90 = np.percentile(z, [10, 50, 90])
    # For SL: z = ln(y - ξ) => exp(z) = y - ξ
    # Using median and spread
    xi = p10 - (p50 - p10) * 0.1  # approximate
    lambda_ = p90 - p10
    if lambda_ <= 0:
        raise ValueError("Invalid lambda for SL")
    transformed = np.log(z - xi)  # This is the normal variate
    return {"xi": float(xi), "lambda": float(lambda_)}, transformed


def _fit_johnson_su(z: np.ndarray) -> Tuple[Dict[str, float], np.ndarray]:
    """Fit Johnson SU (unbounded): sinh⁻¹((y - ξ)/λ) ~ N(0,1)."""
    # SU: y = ξ + λ * sinh(z)
    # z = sinh⁻¹((y - ξ)/λ)
    # For standardized input, we estimate ξ, λ, γ, δ
    # Simplified: use MLE on transformed variable
    # SU is flexible for unbounded data with skew/kurtosis
    # We'll use a simplified fitting based on moment matching
    from scipy.stats import norm

    # Method of moments for SU parameters
    skew = sc_stats.skew(z)
    kurt = sc_stats.kurtosis(z)

    # Approximate SU parameters (Hill et al. 1976)
    # For standardized data, we want sinh⁻¹((z - ξ)/λ) ~ N(0,1)
    # Using Slifker & Shapiro (1980) percentile method
    z_perc = norm.ppf([0.05, 0.1, 0.5, 0.9, 0.95])
    x_perc = np.percentile(z, [5, 10, 50, 90, 95])

    # Solve for ξ, λ, γ, δ
    # This is a simplified approach; full MLE is more complex
    try:
        # Use a numerical optimization
        def neg_loglik(params):
            xi, lam, gamma, delta = params
            if lam <= 0 or delta <= 0:
                return 1e10
            t = (z - xi) / lam
            # SU: z = xi + lam * sinh((x - gamma) / delta)
            # So x = gamma + delta * asinh(t)
            # Jacobian: delta / (lam * sqrt(1 + t**2))
            x = gamma + delta * np.arcsinh(t)
            log_jac = np.log(delta) - np.log(lam) - 0.5 * np.log(1 + t**2)
            log_pdf = -0.5 * x**2 - 0.5 * np.log(2 * np.pi) + log_jac
            return -np.sum(log_pdf)

        # Initial guess
        xi0 = np.median(z) - 0.5 * (np.percentile(z, 75) - np.percentile(z, 25))
        lam0 = np.std(z) * 2
        gamma0 = 0
        delta0 = 1

        result = minimize_scalar(
            lambda x: neg_loglik((xi0, lam0, gamma0, x)),
            bounds=(0.1, 10),
            method="bounded"
        )
        delta_opt = result.x

        # Re-optimize all params
        from scipy.optimize import minimize
        res = minimize(
            neg_loglik,
            [xi0, lam0, gamma0, delta_opt],
            bounds=[(None, None), (1e-6, None), (None, None), (1e-6, None)],
            method="L-BFGS-B"
        )
        xi, lam, gamma, delta = res.x

        transformed = gamma + delta * np.arcsinh((z - xi) / lam)
        return {"xi": float(xi), "lambda": float(lam), "gamma": float(gamma), "delta": float(delta)}, transformed

    except Exception:
        # Fallback: simple moment matching
        xi = np.mean(z) - 0.5 * np.std(z)
        lam = np.std(z)
        gamma = 0
        delta = 1
        transformed = gamma + delta * np.arcsinh((z - xi) / lam)
        return {"xi": float(xi), "lambda": float(lam), "gamma": float(gamma), "delta": float(delta)}, transformed


def _fit_johnson_sb(z: np.ndarray) -> Tuple[Dict[str, float], np.ndarray]:
    """Fit Johnson SB (bounded): ln((y - ξ)/(ξ + λ - y)) ~ N(0,1)."""
    # SB: y in (ξ, ξ + λ)
    # z = (y - ξ) / (ξ + λ - y)  =>  log(z) ~ N(0,1) after scaling
    min_z, max_z = np.min(z), np.max(z)
    range_z = max_z - min_z
    if range_z == 0:
        raise ValueError("Constant data")

    # Estimate bounds with small padding
    xi = min_z - 0.01 * range_z
    lam = range_z + 0.02 * range_z

    # Transform to (0, 1) then to normal
    u = (z - xi) / lam
    # Clamp to avoid numerical issues
    u = np.clip(u, 1e-10, 1 - 1e-10)
    transformed = np.log(u / (1 - u))  # logit = normal

    # Standardize
    transformed = (transformed - np.mean(transformed)) / np.std(transformed)

    return {"xi": float(xi), "lambda": float(lam)}, transformed


# ─── Helper: Select Best Transformation ───────────────────────────────────────


def select_transformation(
    data: pd.Series,
    require_positive: bool = False,
) -> Tuple[pd.Series, Dict[str, Any]]:
    """
    Automatically select and apply the best transformation.

    Tries (in order):
    1. Box-Cox (if all positive)
    2. Johnson (auto family)
    3. Log (if all positive, simple fallback)

    Returns the one with best Anderson-Darling statistic on transformed data.

    Parameters
    ----------
    data : pd.Series
        Input data.
    require_positive : bool
        If True, skip Johnson (which handles negatives) and force positive-only transforms.

    Returns
    -------
    tuple
        (transformed_data, metadata)
    """
    values = data.dropna().values
    if len(values) < 8:
        raise ValueError("Need at least 8 observations for transformation")

    candidates = []

    # 1. Box-Cox (requires positive)
    if np.all(values > 0):
        try:
            bc_data, bc_lambda, bc_meta = boxcox_transform(data)
            ad_stat = sc_stats.anderson(bc_data, dist="norm").statistic
            candidates.append(("boxcox", bc_data, bc_lambda, bc_meta, ad_stat))
        except Exception as e:
            pass

    # 2. Johnson (handles any real data)
    if not require_positive:
        try:
            j_data, j_meta = johnson_transform(data)
            ad_stat = sc_stats.anderson(j_data, dist="norm").statistic
            candidates.append(("johnson", j_data, j_meta["family"], j_meta, ad_stat))
        except Exception:
            pass

    # 3. Log (simple, if positive)
    if np.all(values > 0):
        try:
            log_data = np.log(values)
            ad_stat = sc_stats.anderson(log_data, dist="norm").statistic
            candidates.append(("log", log_data, 0.0, {"method": "log", "lambda": 0.0}, ad_stat))
        except Exception:
            pass

    if not candidates:
        raise RuntimeError("No transformation succeeded")

    # Pick best by AD statistic (lower is better)
    best = min(candidates, key=lambda x: x[-1])

    method_name = best[0]
    transformed_data = pd.Series(best[1], index=data.dropna().index)

    if method_name == "boxcox":
        metadata = best[3]
        metadata["lambda"] = best[2]
    elif method_name == "johnson":
        metadata = best[3]
    else:  # log
        metadata = best[3]

    metadata["selected_method"] = method_name
    metadata["ad_statistic"] = best[4]

    return transformed_data, metadata


# ─── Non-Normal Capability Analysis ────────────────────────────────────────────


def compute_capability_nonnormal(
    series: pd.Series,
    usl: Optional[float],
    lsl: Optional[float],
    target: Optional[float] = None,
    transformation: Literal["auto", "boxcox", "johnson", "log", "none"] = "auto",
) -> Dict[str, Any]:
    """
    Compute capability indices for non-normal data using transformation.

    Method:
    1. Apply best transformation (Box-Cox / Johnson / Log)
    2. Compute capability on transformed data
    3. Back-transform specification limits to get non-parametric capability

    Or use percentile method (Clements 1989):
    - Cpk = min( (USL - P50) / (P99.865 - P50), (P50 - LSL) / (P50 - P0.135) )
    where percentiles are from fitted distribution.

    Parameters
    ----------
    series : pd.Series
        Measurement data.
    usl, lsl : float
        Specification limits.
    target : float, optional
        Target value.
    transformation : str
        "auto", "boxcox", "johnson", "log", "none"

    Returns
    -------
    dict
        Capability indices with transformation info.
    """
    values = series.dropna()
    n = len(values)
    if n < 20:
        return {"error": "Need at least 20 observations for non-normal capability"}

    # Try transformation
    if transformation == "none":
        # Use percentile method directly on raw data
        return _capability_percentile_method(values, usl, lsl, target)
    elif transformation == "auto":
        try:
            transformed, meta = select_transformation(values)
            method = meta["selected_method"]
        except Exception:
            # Fallback to percentile method
            return _capability_percentile_method(values, usl, lsl, target)
    else:
        # Specific transformation requested
        try:
            if transformation == "boxcox":
                transformed, lambda_val, meta = boxcox_transform(values)
                method = "boxcox"
            elif transformation == "johnson":
                transformed, meta = johnson_transform(values)
                method = "johnson"
            elif transformation == "log":
                transformed = np.log(values)
                meta = {"method": "log"}
                method = "log"
            else:
                return {"error": f"Unknown transformation: {transformation}"}
        except Exception:
            return _capability_percentile_method(values, usl, lsl, target)

    # Compute capability on transformed scale
    # This gives "transformed Cpk" which is valid if transform succeeds
    if usl is not None and lsl is not None:
        # Transform spec limits if possible (for Box-Cox with known lambda)
        if method == "boxcox" and "lambda" in meta:
            lambda_val = meta["lambda"]
            if lambda_val == 0:
                usl_t = np.log(usl)
                lsl_t = np.log(lsl)
            else:
                usl_t = (usl**lambda_val - 1) / lambda_val
                lsl_t = (lsl**lambda_val - 1) / lambda_val
        else:
            # For Johnson/log, we can't easily back-transform specs
            # Use percentile method on raw data as primary
            return _capability_percentile_method(values, usl, lsl, target, transformation_meta=meta)

        # Compute on transformed
        mu_t = np.mean(transformed)
        std_t = np.std(transformed, ddof=1)
        spec_range_t = usl_t - lsl_t
        cpu_t = (usl_t - mu_t) / (3 * std_t)
        cpl_t = (mu_t - lsl_t) / (3 * std_t)
        cpk_t = min(cpu_t, cpl_t)

        return {
            "method": f"transformed_{method}",
            "transformation_meta": meta,
            "Cp": round(spec_range_t / (6 * std_t), 4),
            "Cpk": round(cpk_t, 4),
            "Cpu": round(cpu_t, 4),
            "Cpl": round(cpl_t, 4),
            "note": "Capability on transformed scale; interpret with caution",
        }

    # Fallback
    return _capability_percentile_method(values, usl, lsl, target)


def _capability_percentile_method(
    values: np.ndarray,
    usl: Optional[float],
    lsl: Optional[float],
    target: Optional[float] = None,
    transformation_meta: Optional[Dict] = None,
) -> Dict[str, Any]:
    """
    Non-parametric capability using percentiles (Clements 1989, Bothe 1997).

    Cpk = min( (USL - M) / (P99.865 - M), (M - LSL) / (M - P0.135) )
    where M = median (P50), and percentiles from fitted distribution.

    For non-parametric: use empirical percentiles or fitted distribution percentiles.
    """
    n = len(values)
    sorted_vals = np.sort(values)

    # Empirical percentiles
    def percentile(p: float) -> float:
        idx = p * (n - 1)
        lo = int(np.floor(idx))
        hi = int(np.ceil(idx))
        if lo == hi:
            return float(sorted_vals[lo])
        return float(sorted_vals[lo] + (sorted_vals[hi] - sorted_vals[lo]) * (idx - lo))

    median = percentile(0.5)
    p99_865 = percentile(0.99865)
    p0_135 = percentile(0.00135)

    result: Dict[str, Any] = {"method": "nonparametric_percentile"}

    if usl is not None and lsl is not None:
        cpu = (usl - median) / (p99_865 - median) if p99_865 > median else float("inf")
        cpl = (median - lsl) / (median - p0_135) if median > p0_135 else float("inf")
        cpk = min(cpu, cpl)

        result.update({
            "Cp": None,  # Not defined for non-normal
            "Cpk": round(cpk, 4),
            "Cpu": round(cpu, 4) if cpu != float("inf") else None,
            "Cpl": round(cpl, 4) if cpl != float("inf") else None,
            "median": round(median, 4),
            "P99.865": round(p99_865, 4),
            "P0.135": round(p0_135, 4),
        })

        # DPMO from empirical defect rate
        n_out = int(np.sum((values < lsl) | (values > usl)))
        dpmo = (n_out / n) * 1_000_000
        result["dpmo"] = round(dpmo, 1)
        result["sigma_level"] = round(-sc_stats.norm.ppf(dpmo / 2_000_000) + 1.5, 2)

    elif usl is not None:
        cpu = (usl - median) / (p99_865 - median) if p99_865 > median else float("inf")
        result.update({"Cpu": round(cpu, 4) if cpu != float("inf") else None})
    elif lsl is not None:
        cpl = (median - lsl) / (median - p0_135) if median > p0_135 else float("inf")
        result.update({"Cpl": round(cpl, 4) if cpl != float("inf") else None})

    if transformation_meta:
        result["transformation"] = transformation_meta

    return result


# ─── Attribute Control Charts (p, np, c, u) ────────────────────────────────────


def compute_p_chart(
    defectives: np.ndarray,
    sample_sizes: np.ndarray,
) -> Dict[str, Any]:
    """
    p-chart: proportion of defectives (binomial).

    Parameters
    ----------
    defectives : array
        Number of defective items in each sample.
    sample_sizes : array
        Sample size for each subgroup (can vary).

    Returns
    -------
    dict
        p_bar, UCL, LCL, individual p_i, out-of-control points.
    """
    if len(defectives) != len(sample_sizes):
        raise ValueError("defectives and sample_sizes must have same length")

    n_subgroups = len(defectives)
    p_i = defectives / sample_sizes
    p_bar = np.sum(defectives) / np.sum(sample_sizes)

    # Control limits for each subgroup (varying sample sizes)
    ucl = p_bar + 3 * np.sqrt(p_bar * (1 - p_bar) / sample_sizes)
    lcl = p_bar - 3 * np.sqrt(p_bar * (1 - p_bar) / sample_sizes)
    lcl = np.maximum(lcl, 0)

    ooc = np.where((p_i > ucl) | (p_i < lcl))[0]

    return {
        "chart_type": "p",
        "p_bar": round(float(p_bar), 6),
        "UCL": np.round(ucl, 6).tolist(),
        "LCL": np.round(lcl, 6).tolist(),
        "p_values": np.round(p_i, 6).tolist(),
        "ooc_indices": ooc.tolist(),
        "n_subgroups": n_subgroups,
        "sample_sizes": sample_sizes.tolist(),
    }


def compute_np_chart(
    defectives: np.ndarray,
    sample_size: int,
) -> Dict[str, Any]:
    """
    np-chart: number of defectives (binomial, constant sample size).

    Parameters
    ----------
    defectives : array
        Number of defective items in each sample.
    sample_size : int
        Constant sample size per subgroup.

    Returns
    -------
    dict
        np_bar, UCL, LCL, individual np_i, out-of-control points.
    """
    n_subgroups = len(defectives)
    p_bar = np.mean(defectives) / sample_size
    np_bar = p_bar * sample_size

    std_np = np.sqrt(sample_size * p_bar * (1 - p_bar))
    ucl = np_bar + 3 * std_np
    lcl = max(np_bar - 3 * std_np, 0)

    ooc = np.where((defectives > ucl) | (defectives < lcl))[0]

    return {
        "chart_type": "np",
        "np_bar": round(float(np_bar), 4),
        "p_bar": round(float(p_bar), 6),
        "UCL": round(float(ucl), 4),
        "LCL": round(float(lcl), 4),
        "np_values": defectives.tolist(),
        "ooc_indices": ooc.tolist(),
        "n_subgroups": n_subgroups,
        "sample_size": sample_size,
    }


def compute_c_chart(
    defects: np.ndarray,
) -> Dict[str, Any]:
    """
    c-chart: number of defects per unit (Poisson).

    Parameters
    ----------
    defects : array
        Count of defects in each unit/subgroup (constant area of opportunity).

    Returns
    -------
    dict
        c_bar, UCL, LCL, individual c_i, out-of-control points.
    """
    n_subgroups = len(defects)
    c_bar = float(np.mean(defects))

    std_c = np.sqrt(c_bar)
    ucl = c_bar + 3 * std_c
    lcl = max(c_bar - 3 * std_c, 0)

    ooc = np.where((defects > ucl) | (defects < lcl))[0]

    return {
        "chart_type": "c",
        "c_bar": round(c_bar, 4),
        "UCL": round(float(ucl), 4),
        "LCL": round(float(lcl), 4),
        "c_values": defects.tolist(),
        "ooc_indices": ooc.tolist(),
        "n_subgroups": n_subgroups,
    }


def compute_u_chart(
    defects: np.ndarray,
    sample_sizes: np.ndarray,
) -> Dict[str, Any]:
    """
    u-chart: defects per unit (Poisson, varying area of opportunity).

    Parameters
    ----------
    defects : array
        Number of defects in each subgroup.
    sample_sizes : array
        Area of opportunity (units inspected) per subgroup.

    Returns
    -------
    dict
        u_bar, UCL, LCL, individual u_i, out-of-control points.
    """
    if len(defects) != len(sample_sizes):
        raise ValueError("defects and sample_sizes must have same length")

    n_subgroups = len(defects)
    total_defects = np.sum(defects)
    total_units = np.sum(sample_sizes)
    u_bar = total_defects / total_units

    u_i = defects / sample_sizes
    ucl = u_bar + 3 * np.sqrt(u_bar / sample_sizes)
    lcl = u_bar - 3 * np.sqrt(u_bar / sample_sizes)
    lcl = np.maximum(lcl, 0)

    ooc = np.where((u_i > ucl) | (u_i < lcl))[0]

    return {
        "chart_type": "u",
        "u_bar": round(float(u_bar), 6),
        "UCL": np.round(ucl, 6).tolist(),
        "LCL": np.round(lcl, 6).tolist(),
        "u_values": np.round(u_i, 6).tolist(),
        "ooc_indices": ooc.tolist(),
        "n_subgroups": n_subgroups,
        "sample_sizes": sample_sizes.tolist(),
    }